create table employees_archive (
id int primary key,
sFirstName varchar(25) not null,
sLastName varchar(25) not null,
iAge int not null,
dEmploymentDate date not null,
idJobTitle int not null,
sJobTitleName varchar(40) not null,
mSalary money not null,
idDepartment int not null,
sDepartmentName varchar(120) not null,
sHeadLastName varchar(25) not null)